#! /bin/sh

CROSS="arm-android9-linux-androideabi"
export CROSS

KC_KITSH_LDFLAGS_ADD='-fPIC -fPIE -pie'
export KC_KITSH_LDFLAGS_ADD

./build/make-kit-crosscompile "$@" LDFLAGS=-static-libgcc CFLAGS=-fPIE
